//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.28 at 09:24:51 AM CET 
//


package org.kornogcomputing.bossanova.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.kornog-computing.com/bossanova/V1}bnComponent">
 *       &lt;attribute name="nav" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="cachable" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="text" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="actionCommand" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "bnButton")
public class BnButton
    extends BnComponent
{

    @XmlAttribute(name = "nav")
    protected Boolean nav;
    @XmlAttribute(name = "cachable")
    protected Boolean cachable;
    @XmlAttribute(name = "text")
    protected String text;
    @XmlAttribute(name = "actionCommand")
    protected String actionCommand;

    /**
     * Gets the value of the nav property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNav() {
        return nav;
    }

    /**
     * Sets the value of the nav property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNav(Boolean value) {
        this.nav = value;
    }

    /**
     * Gets the value of the cachable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCachable() {
        return cachable;
    }

    /**
     * Sets the value of the cachable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCachable(Boolean value) {
        this.cachable = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the actionCommand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActionCommand() {
        return actionCommand;
    }

    /**
     * Sets the value of the actionCommand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionCommand(String value) {
        this.actionCommand = value;
    }

}
