//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.28 at 09:24:51 AM CET 
//


package org.kornogcomputing.bossanova.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for bnButtonBarPanel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="bnButtonBarPanel">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.kornog-computing.com/bossanova/V1}bnComponent">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.kornog-computing.com/bossanova/V1}bnButton" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bnButtonBarPanel", propOrder = {
    "bnButton"
})
public class BnButtonBarPanel
    extends BnComponent
{

    protected List<BnButton> bnButton;

    /**
     * Gets the value of the bnButton property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bnButton property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBnButton().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BnButton }
     * 
     * 
     */
    public List<BnButton> getBnButton() {
        if (bnButton == null) {
            bnButton = new ArrayList<BnButton>();
        }
        return this.bnButton;
    }

}
