//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.28 at 09:24:51 AM CET 
//


package org.kornogcomputing.bossanova.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for bnComboBox complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="bnComboBox">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.kornog-computing.com/bossanova/V1}bnComponent">
 *       &lt;attribute name="loadFunction" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bnComboBox")
public class BnComboBox
    extends BnComponent
{

    @XmlAttribute(name = "loadFunction")
    protected String loadFunction;

    /**
     * Gets the value of the loadFunction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoadFunction() {
        return loadFunction;
    }

    /**
     * Sets the value of the loadFunction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoadFunction(String value) {
        this.loadFunction = value;
    }

}
