//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.28 at 09:24:51 AM CET 
//


package org.kornogcomputing.bossanova.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for bnComponent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="bnComponent">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="subPanel" type="{http://www.kornog-computing.com/bossanova/V1}bnSubPanel"/>
 *         &lt;element name="bnlabel" type="{http://www.kornog-computing.com/bossanova/V1}bnLabel"/>
 *         &lt;element name="buttonBar" type="{http://www.kornog-computing.com/bossanova/V1}bnButtonBarPanel"/>
 *         &lt;element name="checkBox" type="{http://www.kornog-computing.com/bossanova/V1}bnCheckBox"/>
 *         &lt;element name="comboBox" type="{http://www.kornog-computing.com/bossanova/V1}bnComboBox"/>
 *         &lt;element name="textField" type="{http://www.kornog-computing.com/bossanova/V1}bnTextField"/>
 *         &lt;element name="scrollPane" type="{http://www.kornog-computing.com/bossanova/V1}bnScrollPane"/>
 *         &lt;element name="separator" type="{http://www.kornog-computing.com/bossanova/V1}bnSeparator"/>
 *         &lt;element name="dateAndTime" type="{http://www.kornog-computing.com/bossanova/V1}bnDateAndTime"/>
 *         &lt;element name="lineBreak" type="{http://www.kornog-computing.com/bossanova/V1}bnLineBreak"/>
 *         &lt;element name="fileChooser" type="{http://www.kornog-computing.com/bossanova/V1}bnFileChooser"/>
 *       &lt;/choice>
 *       &lt;attribute name="bnLevel" type="{http://www.kornog-computing.com/bossanova/V1}level" />
 *       &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="param" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="label" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="mandatory" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bnComponent", propOrder = {
    "subPanel",
    "bnlabel",
    "buttonBar",
    "checkBox",
    "comboBox",
    "textField",
    "scrollPane",
    "separator",
    "dateAndTime",
    "lineBreak",
    "fileChooser"
})
@XmlSeeAlso({
    BnSubPanel.class,
    BnLabel.class,
    BnButtonBarPanel.class,
    BnCheckBox.class,
    BnComboBox.class,
    BnTextField.class,
    BnScrollPane.class,
    BnSeparator.class,
    BnDateAndTime.class,
    BnLineBreak.class,
    BnFileChooser.class,
    BnAsteroMark.class,
    BnPanel.class,
    BnButton.class
})
public class BnComponent {

    protected BnSubPanel subPanel;
    protected BnLabel bnlabel;
    protected BnButtonBarPanel buttonBar;
    protected BnCheckBox checkBox;
    protected BnComboBox comboBox;
    protected BnTextField textField;
    protected BnScrollPane scrollPane;
    protected BnSeparator separator;
    protected BnDateAndTime dateAndTime;
    protected BnLineBreak lineBreak;
    protected BnFileChooser fileChooser;
    @XmlAttribute(name = "bnLevel")
    protected String bnLevel;
    @XmlAttribute(name = "width")
    protected Integer width;
    @XmlAttribute(name = "height")
    protected Integer height;
    @XmlAttribute(name = "param")
    protected String param;
    @XmlAttribute(name = "label")
    protected String label;
    @XmlAttribute(name = "mandatory")
    protected Boolean mandatory;

    /**
     * Gets the value of the subPanel property.
     * 
     * @return
     *     possible object is
     *     {@link BnSubPanel }
     *     
     */
    public BnSubPanel getSubPanel() {
        return subPanel;
    }

    /**
     * Sets the value of the subPanel property.
     * 
     * @param value
     *     allowed object is
     *     {@link BnSubPanel }
     *     
     */
    public void setSubPanel(BnSubPanel value) {
        this.subPanel = value;
    }

    /**
     * Gets the value of the bnlabel property.
     * 
     * @return
     *     possible object is
     *     {@link BnLabel }
     *     
     */
    public BnLabel getBnlabel() {
        return bnlabel;
    }

    /**
     * Sets the value of the bnlabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link BnLabel }
     *     
     */
    public void setBnlabel(BnLabel value) {
        this.bnlabel = value;
    }

    /**
     * Gets the value of the buttonBar property.
     * 
     * @return
     *     possible object is
     *     {@link BnButtonBarPanel }
     *     
     */
    public BnButtonBarPanel getButtonBar() {
        return buttonBar;
    }

    /**
     * Sets the value of the buttonBar property.
     * 
     * @param value
     *     allowed object is
     *     {@link BnButtonBarPanel }
     *     
     */
    public void setButtonBar(BnButtonBarPanel value) {
        this.buttonBar = value;
    }

    /**
     * Gets the value of the checkBox property.
     * 
     * @return
     *     possible object is
     *     {@link BnCheckBox }
     *     
     */
    public BnCheckBox getCheckBox() {
        return checkBox;
    }

    /**
     * Sets the value of the checkBox property.
     * 
     * @param value
     *     allowed object is
     *     {@link BnCheckBox }
     *     
     */
    public void setCheckBox(BnCheckBox value) {
        this.checkBox = value;
    }

    /**
     * Gets the value of the comboBox property.
     * 
     * @return
     *     possible object is
     *     {@link BnComboBox }
     *     
     */
    public BnComboBox getComboBox() {
        return comboBox;
    }

    /**
     * Sets the value of the comboBox property.
     * 
     * @param value
     *     allowed object is
     *     {@link BnComboBox }
     *     
     */
    public void setComboBox(BnComboBox value) {
        this.comboBox = value;
    }

    /**
     * Gets the value of the textField property.
     * 
     * @return
     *     possible object is
     *     {@link BnTextField }
     *     
     */
    public BnTextField getTextField() {
        return textField;
    }

    /**
     * Sets the value of the textField property.
     * 
     * @param value
     *     allowed object is
     *     {@link BnTextField }
     *     
     */
    public void setTextField(BnTextField value) {
        this.textField = value;
    }

    /**
     * Gets the value of the scrollPane property.
     * 
     * @return
     *     possible object is
     *     {@link BnScrollPane }
     *     
     */
    public BnScrollPane getScrollPane() {
        return scrollPane;
    }

    /**
     * Sets the value of the scrollPane property.
     * 
     * @param value
     *     allowed object is
     *     {@link BnScrollPane }
     *     
     */
    public void setScrollPane(BnScrollPane value) {
        this.scrollPane = value;
    }

    /**
     * Gets the value of the separator property.
     * 
     * @return
     *     possible object is
     *     {@link BnSeparator }
     *     
     */
    public BnSeparator getSeparator() {
        return separator;
    }

    /**
     * Sets the value of the separator property.
     * 
     * @param value
     *     allowed object is
     *     {@link BnSeparator }
     *     
     */
    public void setSeparator(BnSeparator value) {
        this.separator = value;
    }

    /**
     * Gets the value of the dateAndTime property.
     * 
     * @return
     *     possible object is
     *     {@link BnDateAndTime }
     *     
     */
    public BnDateAndTime getDateAndTime() {
        return dateAndTime;
    }

    /**
     * Sets the value of the dateAndTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BnDateAndTime }
     *     
     */
    public void setDateAndTime(BnDateAndTime value) {
        this.dateAndTime = value;
    }

    /**
     * Gets the value of the lineBreak property.
     * 
     * @return
     *     possible object is
     *     {@link BnLineBreak }
     *     
     */
    public BnLineBreak getLineBreak() {
        return lineBreak;
    }

    /**
     * Sets the value of the lineBreak property.
     * 
     * @param value
     *     allowed object is
     *     {@link BnLineBreak }
     *     
     */
    public void setLineBreak(BnLineBreak value) {
        this.lineBreak = value;
    }

    /**
     * Gets the value of the fileChooser property.
     * 
     * @return
     *     possible object is
     *     {@link BnFileChooser }
     *     
     */
    public BnFileChooser getFileChooser() {
        return fileChooser;
    }

    /**
     * Sets the value of the fileChooser property.
     * 
     * @param value
     *     allowed object is
     *     {@link BnFileChooser }
     *     
     */
    public void setFileChooser(BnFileChooser value) {
        this.fileChooser = value;
    }

    /**
     * Gets the value of the bnLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBnLevel() {
        return bnLevel;
    }

    /**
     * Sets the value of the bnLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBnLevel(String value) {
        this.bnLevel = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWidth(Integer value) {
        this.width = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHeight(Integer value) {
        this.height = value;
    }

    /**
     * Gets the value of the param property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParam() {
        return param;
    }

    /**
     * Sets the value of the param property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParam(String value) {
        this.param = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the mandatory property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMandatory() {
        return mandatory;
    }

    /**
     * Sets the value of the mandatory property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMandatory(Boolean value) {
        this.mandatory = value;
    }

}
