//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.28 at 09:24:51 AM CET 
//


package org.kornogcomputing.bossanova.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.kornogcomputing.bossanova.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.kornogcomputing.bossanova.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BnLabel }
     * 
     */
    public BnLabel createBnLabel() {
        return new BnLabel();
    }

    /**
     * Create an instance of {@link BnFileChooser }
     * 
     */
    public BnFileChooser createBnFileChooser() {
        return new BnFileChooser();
    }

    /**
     * Create an instance of {@link BnComboBox }
     * 
     */
    public BnComboBox createBnComboBox() {
        return new BnComboBox();
    }

    /**
     * Create an instance of {@link Row }
     * 
     */
    public Row createRow() {
        return new Row();
    }

    /**
     * Create an instance of {@link BnPanel }
     * 
     */
    public BnPanel createBnPanel() {
        return new BnPanel();
    }

    /**
     * Create an instance of {@link BnButton }
     * 
     */
    public BnButton createBnButton() {
        return new BnButton();
    }

    /**
     * Create an instance of {@link BnAsteroMark }
     * 
     */
    public BnAsteroMark createBnAsteroMark() {
        return new BnAsteroMark();
    }

    /**
     * Create an instance of {@link BnComponent }
     * 
     */
    public BnComponent createBnComponent() {
        return new BnComponent();
    }

    /**
     * Create an instance of {@link BnCheckBox }
     * 
     */
    public BnCheckBox createBnCheckBox() {
        return new BnCheckBox();
    }

    /**
     * Create an instance of {@link BnSeparator }
     * 
     */
    public BnSeparator createBnSeparator() {
        return new BnSeparator();
    }

    /**
     * Create an instance of {@link BnLineBreak }
     * 
     */
    public BnLineBreak createBnLineBreak() {
        return new BnLineBreak();
    }

    /**
     * Create an instance of {@link BnScrollPane }
     * 
     */
    public BnScrollPane createBnScrollPane() {
        return new BnScrollPane();
    }

    /**
     * Create an instance of {@link BnDateAndTime }
     * 
     */
    public BnDateAndTime createBnDateAndTime() {
        return new BnDateAndTime();
    }

    /**
     * Create an instance of {@link BnSubPanel }
     * 
     */
    public BnSubPanel createBnSubPanel() {
        return new BnSubPanel();
    }

    /**
     * Create an instance of {@link BnTextField }
     * 
     */
    public BnTextField createBnTextField() {
        return new BnTextField();
    }

    /**
     * Create an instance of {@link BnButtonBarPanel }
     * 
     */
    public BnButtonBarPanel createBnButtonBarPanel() {
        return new BnButtonBarPanel();
    }

}
