//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.28 at 09:24:51 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.kornog-computing.com/bossanova/V1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.kornogcomputing.bossanova.xml;
