//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.08 at 03:18:47 PM CET 
//


package org.kornogcomputing.bossanova.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BNBUTTONBARPANEL complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BNBUTTONBARPANEL">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.kornog-computing.com/bossanova/V1}BNCOMPONENT">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.kornog-computing.com/bossanova/V1}BNBUTTON" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BNBUTTONBARPANEL", propOrder = {
    "bnbutton"
})
public class BNBUTTONBARPANEL
    extends BNCOMPONENT
{

    @XmlElement(name = "BNBUTTON")
    protected List<BNBUTTON> bnbutton;

    /**
     * Gets the value of the bnbutton property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bnbutton property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBNBUTTON().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BNBUTTON }
     * 
     * 
     */
    public List<BNBUTTON> getBNBUTTON() {
        if (bnbutton == null) {
            bnbutton = new ArrayList<BNBUTTON>();
        }
        return this.bnbutton;
    }

}
