//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.06 at 11:12:12 AM CET 
//


package org.kornogcomputing.bossanova.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BNFIELD.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="BNFIELD">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Validate"/>
 *     &lt;enumeration value="ValidateForPNO"/>
 *     &lt;enumeration value="Cancel"/>
 *     &lt;enumeration value="Delete"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "BNFIELD")
@XmlEnum
public enum BNFIELD {

    @XmlEnumValue("Validate")
    VALIDATE("Validate"),
    @XmlEnumValue("ValidateForPNO")
    VALIDATE_FOR_PNO("ValidateForPNO"),
    @XmlEnumValue("Cancel")
    CANCEL("Cancel"),
    @XmlEnumValue("Delete")
    DELETE("Delete");
    private final String value;

    BNFIELD(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BNFIELD fromValue(String v) {
        for (BNFIELD c: BNFIELD.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
