//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.08 at 03:18:47 PM CET 
//


package org.kornogcomputing.bossanova.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.kornogcomputing.bossanova.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _BNASTEROMARKLabel_QNAME = new QName("http://www.kornog-computing.com/bossanova/V1", "label");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.kornogcomputing.bossanova.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BNSEPARATOR }
     * 
     */
    public BNSEPARATOR createBNSEPARATOR() {
        return new BNSEPARATOR();
    }

    /**
     * Create an instance of {@link BNTEXTFIELD }
     * 
     */
    public BNTEXTFIELD createBNTEXTFIELD() {
        return new BNTEXTFIELD();
    }

    /**
     * Create an instance of {@link COLONNE }
     * 
     */
    public COLONNE createCOLONNE() {
        return new COLONNE();
    }

    /**
     * Create an instance of {@link BNLINEBREAK }
     * 
     */
    public BNLINEBREAK createBNLINEBREAK() {
        return new BNLINEBREAK();
    }

    /**
     * Create an instance of {@link BNPANEL }
     * 
     */
    public BNPANEL createBNPANEL() {
        return new BNPANEL();
    }

    /**
     * Create an instance of {@link BNCOMPONENT }
     * 
     */
    public BNCOMPONENT createBNCOMPONENT() {
        return new BNCOMPONENT();
    }

    /**
     * Create an instance of {@link BNASTEROMARK }
     * 
     */
    public BNASTEROMARK createBNASTEROMARK() {
        return new BNASTEROMARK();
    }

    /**
     * Create an instance of {@link BNCOMBOBOX }
     * 
     */
    public BNCOMBOBOX createBNCOMBOBOX() {
        return new BNCOMBOBOX();
    }

    /**
     * Create an instance of {@link OBJECTS }
     * 
     */
    public OBJECTS createOBJECTS() {
        return new OBJECTS();
    }

    /**
     * Create an instance of {@link BNBUTTON }
     * 
     */
    public BNBUTTON createBNBUTTON() {
        return new BNBUTTON();
    }

    /**
     * Create an instance of {@link BNCHECKBOX }
     * 
     */
    public BNCHECKBOX createBNCHECKBOX() {
        return new BNCHECKBOX();
    }

    /**
     * Create an instance of {@link BNLABEL }
     * 
     */
    public BNLABEL createBNLABEL() {
        return new BNLABEL();
    }

    /**
     * Create an instance of {@link BNDATEANDTIME }
     * 
     */
    public BNDATEANDTIME createBNDATEANDTIME() {
        return new BNDATEANDTIME();
    }

    /**
     * Create an instance of {@link BNBUTTONBARPANEL }
     * 
     */
    public BNBUTTONBARPANEL createBNBUTTONBARPANEL() {
        return new BNBUTTONBARPANEL();
    }

    /**
     * Create an instance of {@link BNSCROLLPANE }
     * 
     */
    public BNSCROLLPANE createBNSCROLLPANE() {
        return new BNSCROLLPANE();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BNLABEL }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.kornog-computing.com/bossanova/V1", name = "label", scope = BNASTEROMARK.class)
    public JAXBElement<BNLABEL> createBNASTEROMARKLabel(BNLABEL value) {
        return new JAXBElement<BNLABEL>(_BNASTEROMARKLabel_QNAME, BNLABEL.class, BNASTEROMARK.class, value);
    }

}
