//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.08 at 03:18:47 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.kornog-computing.com/bossanova/V1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.kornogcomputing.bossanova.xml;
